# Script to convert unified-index.md to toc.yml format
# Generated by: GitHub Copilot
# Date: 2026-01-28

param(
    [string]$InputFile = (Join-Path $PSScriptRoot "..\reference\unified-index.md"),
    [string]$OutputFile = (Join-Path $PSScriptRoot "..\reference\api-toc.yml"),
    [string]$BaseHrefPath = "reference/"
)

Write-Host "Converting unified index to toc.yml format..." -ForegroundColor Cyan
Write-Host "Input File: $InputFile" -ForegroundColor Yellow
Write-Host "Output File: $OutputFile" -ForegroundColor Yellow

if (-not (Test-Path $InputFile)) {
    Write-Error "Input file not found: $InputFile"
    exit 1
}

# Read the unified index
$content = Get-Content $InputFile -Raw -Encoding UTF8

# Initialize YAML content
$yaml = @()

# Function to convert markdown link to YAML entry
function Convert-MarkdownLink {
    param(
        [string]$Line,
        [int]$IndentLevel = 1
    )
    
    # Extract link text and URL from markdown format: * [Text](url.md#anchor): Description
    if ($Line -match '^\s*\*\s+\[([^\]]+)\]\(([^)#]+)(?:#[^)]+)?\)(?::\s*(.*))?') {
        $name = $matches[1]
        $href = $matches[2]
        $description = $matches[3]
        
        # Clean up escaped underscores in names
        $name = $name -replace '\\_', '_'
        
        # Create indentation (2 spaces per level)
        $indent = "  " * $IndentLevel
        
        # Build YAML entry with proper indentation
        $yamlEntry = "${indent}- name: $name`n"
        $yamlEntry += "${indent}  href: ${BaseHrefPath}${href}"
        
        return $yamlEntry
    }
    
    return $null
}

# Parse the content line by line
$lines = $content -split "`n"
$currentSection = $null

foreach ($line in $lines) {
    # Check for section headers (## Title)
    if ($line -match '^##\s+(.+)$') {
        $sectionTitle = $matches[1].Trim()
        
        # Add section as a top-level item with nested items
        $yaml += "- name: $sectionTitle"
        $yaml += "  items:"
        $currentSection = $sectionTitle
        continue
    }
    
    # Process markdown links
    if ($line -match '^\s*\*\s+\[') {
        $yamlEntry = Convert-MarkdownLink -Line $line -IndentLevel 1
        if ($yamlEntry) {
            $yaml += $yamlEntry
        }
    }
}

# Write the YAML file
$yamlContent = $yaml -join "`n"
$yamlContent | Out-File -FilePath $OutputFile -Encoding UTF8 -Force

Write-Host "`ntoc.yml file generated successfully!" -ForegroundColor Green
Write-Host "Output: $OutputFile" -ForegroundColor Green

# Display statistics
$itemCount = ([regex]::Matches($yamlContent, '- name:')).Count
$sectionCount = ([regex]::Matches($yamlContent, 'items:')).Count

Write-Host "`nStatistics:" -ForegroundColor Cyan
Write-Host "  Total sections: $sectionCount"
Write-Host "  Total items: $($itemCount - $sectionCount)"
