# Script to copy Markdown reference files to markdown folder
# Generated by: GitHub Copilot
# Date: 2026-01-28

param(
    [string]$SourceDir = (Join-Path $PSScriptRoot "..\..\documentation\doxygen\reference"),
    [string]$DestDir = (Join-Path $PSScriptRoot "..\reference"),
    [switch]$IncludeScripts = $false
)

Write-Host "====================================" -ForegroundColor Magenta
Write-Host "Copy Reference Markdown Files" -ForegroundColor Magenta
Write-Host "====================================" -ForegroundColor Magenta
Write-Host ""

# Verify source directory exists
if (-not (Test-Path $SourceDir)) {
    Write-Error "Source directory not found: $SourceDir"
    exit 1
}

Write-Host "Source: $SourceDir" -ForegroundColor Cyan
Write-Host "Destination: $DestDir" -ForegroundColor Cyan
Write-Host ""

# Create destination directory if it doesn't exist
if (-not (Test-Path $DestDir)) {
    Write-Host "Creating destination directory..." -ForegroundColor Yellow
    New-Item -Path $DestDir -ItemType Directory -Force | Out-Null
    Write-Host "  Created: $DestDir" -ForegroundColor Green
} else {
    Write-Host "Destination directory exists" -ForegroundColor Green
}

Write-Host ""

# Get all markdown files from source
Write-Host "Scanning for Markdown files..." -ForegroundColor Cyan
$markdownFiles = Get-ChildItem -Path $SourceDir -Filter "*.md" -File

if ($markdownFiles.Count -eq 0) {
    Write-Warning "No Markdown files found in source directory"
    exit 0
}

Write-Host "  Found $($markdownFiles.Count) Markdown files" -ForegroundColor White
Write-Host ""

# Copy files
Write-Host "Copying files..." -ForegroundColor Cyan
$copiedCount = 0
$skippedCount = 0

foreach ($file in $markdownFiles) {
    $destPath = Join-Path $DestDir $file.Name
    
    try {
        Copy-Item -Path $file.FullName -Destination $destPath -Force
        $copiedCount++
        Write-Host "  Copied: $($file.Name)" -ForegroundColor Green
    }
    catch {
        Write-Warning "  Failed to copy $($file.Name): $_"
        $skippedCount++
    }
}

# Optionally copy scripts
if ($IncludeScripts) {
    Write-Host ""
    Write-Host "Copying PowerShell scripts..." -ForegroundColor Cyan
    $scriptFiles = Get-ChildItem -Path $SourceDir -Filter "*.ps1" -File
    
    foreach ($file in $scriptFiles) {
        $destPath = Join-Path $DestDir $file.Name
        
        try {
            Copy-Item -Path $file.FullName -Destination $destPath -Force
            Write-Host "  Copied: $($file.Name)" -ForegroundColor Green
        }
        catch {
            Write-Warning "  Failed to copy $($file.Name): $_"
        }
    }
}

# Copy any additional files like compound-list.js if they exist
Write-Host ""
Write-Host "Checking for additional resource files..." -ForegroundColor Cyan
$jsFiles = Get-ChildItem -Path $SourceDir -Filter "*.js" -File

if ($jsFiles.Count -gt 0) {
    Write-Host "  Found $($jsFiles.Count) JavaScript files" -ForegroundColor White
    foreach ($file in $jsFiles) {
        $destPath = Join-Path $DestDir $file.Name
        Copy-Item -Path $file.FullName -Destination $destPath -Force
        Write-Host "  Copied: $($file.Name)" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "====================================" -ForegroundColor Green
Write-Host "Copy completed successfully!" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  Markdown files copied: $copiedCount" -ForegroundColor White
if ($skippedCount -gt 0) {
    Write-Host "  Files skipped (errors): $skippedCount" -ForegroundColor Yellow
}
Write-Host "  Destination: $DestDir" -ForegroundColor White
Write-Host ""

# Note about paths
Write-Host "Note:" -ForegroundColor Yellow
Write-Host "  The main toc.yml already uses reference/ paths" -ForegroundColor White
Write-Host "  These now correctly point to markdown/reference/ folder" -ForegroundColor White
Write-Host ""
