# Script to generate a unified index.md from all nested index and contents files
# Generated by: GitHub Copilot
# Date: 2026-01-28

param(
    [string]$SourceDir = (Join-Path $PSScriptRoot "..\reference"),
    [string]$OutputFile = ""
)

# Set default output file if not specified
if ([string]::IsNullOrEmpty($OutputFile)) {
    $OutputFile = Join-Path $SourceDir "unified-index.md"
}

Write-Host "Generating unified index from Doxygen MD files..." -ForegroundColor Cyan
Write-Host "Source Directory: $SourceDir" -ForegroundColor Yellow
Write-Host "Output File: $OutputFile" -ForegroundColor Yellow

# Initialize output content
$content = @"
# Simulation Framework API Reference

This is a unified index of all classes, structures, namespaces, files, and directories in the Simulation Framework.

"@

# Function to extract links from markdown files
function Extract-Links {
    param(
        [string]$FilePath,
        [string]$SectionTitle
    )
    
    if (-not (Test-Path $FilePath)) {
        Write-Warning "File not found: $FilePath"
        return ""
    }
    
    Write-Host "Processing: $FilePath" -ForegroundColor Gray
    
    $fileContent = Get-Content $FilePath -Raw -Encoding UTF8
    
    # Extract markdown list items with links
    $links = @()
    $lines = $fileContent -split "`n"
    
    foreach ($line in $lines) {
        # Match lines that start with * and contain a link
        if ($line -match '^\s*\*\s+\[') {
            $links += $line.TrimStart()
        }
    }
    
    if ($links.Count -gt 0) {
        $section = "`n## $SectionTitle`n`n"
        $section += ($links -join "`n")
        $section += "`n"
        return $section
    }
    
    return ""
}

# Process all content files in order
$sections = @(
    @{File = "namespace_contents.md"; Title = "Namespaces"},
    @{File = "class_contents.md"; Title = "Classes"},
    @{File = "struct_contents.md"; Title = "Structures"},
    @{File = "file_contents.md"; Title = "Files"},
    @{File = "dir_contents.md"; Title = "Directories"},
    @{File = "global_contents.md"; Title = "Global Definitions"}
)

foreach ($section in $sections) {
    $filePath = Join-Path $SourceDir $section.File
    $sectionContent = Extract-Links -FilePath $filePath -SectionTitle $section.Title
    if ($sectionContent) {
        $content += $sectionContent
    }
}

# Also process index files if they contain additional information
Write-Host "`nProcessing index files for additional content..." -ForegroundColor Cyan

$indexSections = @(
    @{File = "namespace_index.md"; Title = "Namespace Index"},
    @{File = "class_index.md"; Title = "Class Index"},
    @{File = "struct_index.md"; Title = "Structure Index"},
    @{File = "file_index.md"; Title = "File Index"},
    @{File = "dir_index.md"; Title = "Directory Index"},
    @{File = "global_index.md"; Title = "Global Index"}
)

foreach ($section in $indexSections) {
    $filePath = Join-Path $SourceDir $section.File
    if (Test-Path $filePath) {
        $indexContent = Get-Content $filePath -Raw -Encoding UTF8
        # Only add if it has different content than the contents file
        if ($indexContent -match '\[.*\]\(.*\.md') {
            Write-Host "  Found additional content in: $($section.File)" -ForegroundColor Gray
        }
    }
}

# Write the unified index
$content | Out-File -FilePath $OutputFile -Encoding UTF8 -Force

Write-Host "`nUnified index generated successfully!" -ForegroundColor Green
Write-Host "Output: $OutputFile" -ForegroundColor Green

# Display statistics
$lineCount = ($content -split "`n").Count
$linkCount = ([regex]::Matches($content, '\[.*?\]\(.*?\.md.*?\)')).Count

Write-Host "`nStatistics:" -ForegroundColor Cyan
Write-Host "  Total lines: $lineCount"
Write-Host "  Total links: $linkCount"
