# Script to merge api-toc.yml with toc-md-files.yml to create toc.yml
# Generated by: GitHub Copilot
# Date: 2026-01-28

param(
    [string]$ApiTocPath = (Join-Path $PSScriptRoot "..\reference\api-toc.yml"),
    [string]$MdFilesTocPath = (Join-Path $PSScriptRoot "..\toc-md-files.yml"),
    [string]$OutputTocPath = (Join-Path $PSScriptRoot "..\toc.yml"),
    [string]$BackupPath = ""
)

Write-Host "====================================" -ForegroundColor Magenta
Write-Host "TOC Merge Script" -ForegroundColor Magenta
Write-Host "====================================" -ForegroundColor Magenta
Write-Host ""

# Verify source files exist
if (-not (Test-Path $ApiTocPath)) {
    Write-Error "API TOC file not found: $ApiTocPath"
    exit 1
}

if (-not (Test-Path $MdFilesTocPath)) {
    Write-Error "Markdown files TOC not found: $MdFilesTocPath"
    exit 1
}

Write-Host "Source Files:" -ForegroundColor Cyan
Write-Host "  API TOC: $ApiTocPath" -ForegroundColor White
Write-Host "  Markdown Files TOC: $MdFilesTocPath" -ForegroundColor White
Write-Host "  Output: $OutputTocPath" -ForegroundColor White
Write-Host ""

# Create backup if output file exists
if (Test-Path $OutputTocPath) {
    if ([string]::IsNullOrEmpty($BackupPath)) {
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $BackupPath = $OutputTocPath -replace '\.yml$', "_backup_$timestamp.yml"
    }
    
    Write-Host "Creating backup of existing toc.yml..." -ForegroundColor Cyan
    Copy-Item -Path $OutputTocPath -Destination $BackupPath -Force
    Write-Host "  Backup created: $BackupPath" -ForegroundColor Green
    Write-Host ""
}

# Read the files
Write-Host "Reading files..." -ForegroundColor Cyan
$mdFilesTocContent = Get-Content $MdFilesTocPath -Raw -Encoding UTF8
# Read the files
Write-Host "Reading files..." -ForegroundColor Cyan
$mdFilesTocContent = Get-Content $MdFilesTocPath -Raw -Encoding UTF8
$apiTocContent = Get-Content $ApiTocPath -Raw -Encoding UTF8

# Add proper indentation to api-toc content
# The api-toc.yml has sections starting with "- name:" at the root level
# We need to indent everything by 1 level (2 spaces) to fit under "items:"
Write-Host "Adjusting indentation..." -ForegroundColor Cyan

$apiTocLines = $apiTocContent -split "`r?`n"
$indentedApiToc = @()

foreach ($line in $apiTocLines) {
    if ($line.Trim() -eq '') {
        # Skip empty lines
        continue
    }
    # Add 2 spaces of indentation to each line
    $indentedApiToc += "  $line"
}

# Build the Reference section
$referenceSection = @"

- name: Reference
  items:
$($indentedApiToc -join "`n")
"@

# Merge: toc-md-files.yml content + Reference section
Write-Host "Merging content..." -ForegroundColor Cyan
$mergedContent = $mdFilesTocContent.TrimEnd() + $referenceSection

# Write the merged content to toc.yml
Write-Host "Writing merged TOC to toc.yml..." -ForegroundColor Cyan
$mergedContent | Out-File -FilePath $OutputTocPath -Encoding UTF8 -Force

Write-Host ""
Write-Host "====================================" -ForegroundColor Green
Write-Host "Merge completed successfully!" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  Source 1: $MdFilesTocPath" -ForegroundColor White
Write-Host "  Source 2: $ApiTocPath" -ForegroundColor White
Write-Host "  Output: $OutputTocPath" -ForegroundColor White
if (Test-Path $BackupPath) {
    Write-Host "  Backup: $BackupPath" -ForegroundColor White
}
Write-Host ""

# Count sections added
$sectionCount = ([regex]::Matches($referenceSection, '^\s+- name:', [System.Text.RegularExpressions.RegexOptions]::Multiline)).Count
Write-Host "  Sections added under Reference: $sectionCount" -ForegroundColor White
Write-Host ""
Write-Host "Note: Review the merged toc.yml file to ensure proper formatting." -ForegroundColor Yellow
