# Master script to run complete documentation generation workflow
# Generated by: GitHub Copilot
# Date: 2026-01-28

param(
    [string]$ReferenceDir = (Join-Path $PSScriptRoot "..\reference"),
    [string]$MainTocPath = (Join-Path $PSScriptRoot "..\toc.yml")
)

Write-Host "====================================" -ForegroundColor Magenta
Write-Host "Documentation Generation Workflow" -ForegroundColor Magenta
Write-Host "====================================" -ForegroundColor Magenta
Write-Host ""

# Step 0: Copy files from doxygen/reference to markdown/reference
Write-Host "Step 0: Copying Markdown files to markdown/reference..." -ForegroundColor Cyan
& (Join-Path $PSScriptRoot "copy-to-markdown.ps1")

if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne $null) {
    Write-Error "Failed to copy Markdown files"
    exit 1
}

Write-Host ""

# Step 1: Generate unified index
Write-Host "Step 1: Generating unified index..." -ForegroundColor Cyan
& (Join-Path $PSScriptRoot "generate-unified-index.ps1") -SourceDir $ReferenceDir

if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne $null) {
    Write-Error "Failed to generate unified index"
    exit 1
}

Write-Host ""

# Step 2: Convert to TOC
Write-Host "Step 2: Converting to toc.yml..." -ForegroundColor Cyan
& (Join-Path $PSScriptRoot "convert-to-toc.ps1") -InputFile (Join-Path $ReferenceDir "unified-index.md") -OutputFile (Join-Path $ReferenceDir "api-toc.yml")

if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne $null) {
    Write-Error "Failed to convert to toc.yml"
    exit 1
}

Write-Host ""

# Step 3: Merge to main TOC
Write-Host "Step 3: Merging to create toc.yml..." -ForegroundColor Cyan
& (Join-Path $PSScriptRoot "merge-toc.ps1") -ApiTocPath (Join-Path $ReferenceDir "api-toc.yml") -MdFilesTocPath (Join-Path (Split-Path $ReferenceDir -Parent) "toc-md-files.yml") -OutputTocPath $MainTocPath

if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne $null) {
    Write-Error "Failed to merge to main toc.yml"
    exit 1
}

Write-Host ""
Write-Host "====================================" -ForegroundColor Green
Write-Host "All tasks completed successfully!" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green
Write-Host ""
Write-Host "Generated files:" -ForegroundColor Cyan
Write-Host "  1. markdown/reference/*.md - All copied Markdown files" -ForegroundColor White
Write-Host "  2. unified-index.md - Complete index of all documentation" -ForegroundColor White
Write-Host "  3. api-toc.yml - Table of contents in YAML format" -ForegroundColor White
Write-Host "  4. Main toc.yml updated with Reference section" -ForegroundColor White
Write-Host ""
Write-Host "Location: $ReferenceDir" -ForegroundColor White
Write-Host ""
