#!/usr/bin/env bash

################################################################################
# Promotes sandbox documentation changes to main by cherry-picking merged PRs
# labeled "ready-for-prod".
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/_promotion_lib.sh"

readonly DRY_RUN="${DRY_RUN:-false}"

cherry_pick_commit() {
  local _commit="$1"

  if git cherry-pick -x "${_commit}"; then
    return 0
  fi

  git cherry-pick --abort >/dev/null 2>&1 || true

  if git cherry-pick -x -m 1 "${_commit}"; then
    return 0
  fi

  git cherry-pick --abort >/dev/null 2>&1 || true
  return 1
}

promote_pull_request() {
  local _pr_number="$1"
  local _merge_commit _title _product_dir _branch_name _prod_pr_url

  _merge_commit=$(gh pr view "${_pr_number}" --json mergeCommit --jq '.mergeCommit.oid')
  _title=$(gh pr view "${_pr_number}" --json title --jq '.title')

  if [[ -z "${_merge_commit}" || "${_merge_commit}" == "null" ]]; then
    log_error "Sandbox PR #${_pr_number} is not merged."
    return 1
  fi

  log_info "Processing sandbox PR #${_pr_number} (${_merge_commit})"

  if ! _product_dir=$(get_product_version_dir "${_merge_commit}"); then
    set_pr_labels "${_pr_number}" "${FAILED_LABEL}"
    return 1
  fi

  log_info "Detected product path: ${_product_dir}"

  if commit_on_branch "${_merge_commit}" "main"; then
    log_info "Commit ${_merge_commit} is already on main. Marking PR #${_pr_number} as promoted."
    gh pr edit "${_pr_number}" --remove-label "${READY_LABEL}" >/dev/null || true
    set_pr_labels "${_pr_number}" "${DONE_LABEL}"
    return 0
  fi

  if ! commit_on_branch "${_merge_commit}" "sandbox"; then
    log_error "Commit ${_merge_commit} is not contained in origin/sandbox."
    set_pr_labels "${_pr_number}" "${FAILED_LABEL}"
    return 1
  fi

  _branch_name="promote/pr-${_pr_number}-$(git rev-parse --short "${_merge_commit}")"

  if [[ "${DRY_RUN}" == "true" ]]; then
    log_info "[dry run] Would cherry-pick ${_merge_commit} onto ${_branch_name} and open a PR to main."
    return 0
  fi

  git checkout -B "${_branch_name}" origin/main
  if ! cherry_pick_commit "${_merge_commit}"; then
    log_error "Cherry-pick failed for sandbox PR #${_pr_number} (${_merge_commit})."
    git checkout - >/dev/null 2>&1 || git checkout main >/dev/null 2>&1 || true
    git branch -D "${_branch_name}" >/dev/null 2>&1 || true
    set_pr_labels "${_pr_number}" "${FAILED_LABEL}"
    return 1
  fi

  git push --force-with-lease origin "${_branch_name}"

  _prod_pr_url=$(gh pr create \
    --base main \
    --head "${_branch_name}" \
    --title "Promote to prod: ${_title}" \
    --body "$(cat <<EOF
## Production promotion

This PR was created automatically from sandbox PR #${_pr_number}.

- Sandbox merge commit: \`${_merge_commit}\`
- Product path: \`${_product_dir}\`

Merging this PR publishes the documentation to production.

---

_Auto-generated by the sandbox-to-main promotion workflow._
EOF
)")

  gh pr edit "${_pr_number}" --remove-label "${READY_LABEL}" >/dev/null || true
  set_pr_labels "${_pr_number}" "${DONE_LABEL}"

  gh pr comment "${_pr_number}" --body "$(cat <<EOF
Queued for production promotion.

Production PR: ${_prod_pr_url}
EOF
)"

  log_info "Created production PR: ${_prod_pr_url}"
  return 0
}

list_ready_pull_requests() {
  gh pr list \
    --state merged \
    --base sandbox \
    --label "${READY_LABEL}" \
    --limit 200 \
    --json number,labels \
    --jq '[.[] | select([.labels[].name] | contains(["'"${DONE_LABEL}"'"]) | not) | select([.labels[].name] | contains(["'"${FAILED_LABEL}"'"]) | not)] | .[].number'
}

main() {
  local _pr_numbers _pr_number _failures=0

  validate_dependencies
  git fetch origin main sandbox --prune

  mapfile -t _pr_numbers < <(list_ready_pull_requests)

  if [[ ${#_pr_numbers[@]} -eq 0 ]]; then
    log_info "No sandbox PRs are queued for production promotion."
    exit 0
  fi

  log_info "Found ${#_pr_numbers[@]} sandbox PR(s) queued for promotion."

  for _pr_number in "${_pr_numbers[@]}"; do
    if [[ -z "${_pr_number}" ]]; then
      continue
    fi

    if ! promote_pull_request "${_pr_number}"; then
      _failures=$((_failures + 1))
    fi
  done

  if [[ ${_failures} -gt 0 ]]; then
    log_error "${_failures} promotion(s) failed."
    exit 1
  fi

  log_info "Promotion run completed successfully."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
