name: 'Product Collection'
id: product_collection
description: ''
terms:
  - '3D Design'
  - 'Acoustics Simulation'
  - 'Additive'
  - 'Autonomous Vehicle Simulation'
  - 'Cloud'
  - 'Connect'
  - 'Digital Mission Engineering'
  - 'Digital Twin'
  - 'Electronics'
  - 'Embedded Software'
  - 'Fluids'
  - 'Materials'
  - 'Optics'
  - 'Photonics'
  - 'Safety Analysis'
  - 'Semiconductors'
  - 'Structures'
