name: Product
id: product
description: 'Product categories.'
terms:
  - 'Ansys ID Portal'
  - 'Ansys ID SSO'
  - 'AVxcelerate Autonomy'
  - 'AVxcelerate Sensors'
  - 'Composite PrepPost'
  - 'Common Fluids Format'
  - 'Discovery'
  - 'DPF'
  - 'Dynamic Reporting'
  - 'Ensight'
  - 'Granta MI'
  - 'Mechanical'
  - 'ModelCenter'
  - 'Motion'
  - 'optiSLang'
  - 'Prime Mesh'
  - 'Rigid Body Dynamics'
  - 'Rocky'
  - 'Scade One'
  - 'Sherlock'
  - 'SimAI'
  - 'Sound'
  - 'Speos'
  - 'System Coupling'
  - 'Thermal Desktop'
  - 'Zemax'
