var hierarchy =
[
    [ "IRockyAdhesionOutputData", "structIRockyAdhesionOutputData.xhtml", null ],
    [ "IRockyBreakableParticle", "structIRockyBreakableParticle.xhtml", null ],
    [ "IRockyCFDModel", "structIRockyCFDModel.xhtml", null ],
    [ "IRockyCFDProperties", "structIRockyCFDProperties.xhtml", null ],
    [ "IRockyCloudPoint", "structIRockyCloudPoint.xhtml", null ],
    [ "IRockyContact", "structIRockyContact.xhtml", null ],
    [ "IRockyContactDataRecorder", "structIRockyContactDataRecorder.xhtml", null ],
    [ "IRockyContactIntermediateData", "structIRockyContactIntermediateData.xhtml", null ],
    [ "IRockyContactOutputData", "structIRockyContactOutputData.xhtml", null ],
    [ "IRockyContactScalars", "structIRockyContactScalars.xhtml", null ],
    [ "IRockyContactScalarsModel", "structIRockyContactScalarsModel.xhtml", null ],
    [ "IRockyCurveCollectionData", "structIRockyCurveCollectionData.xhtml", null ],
    [ "IRockyDeviceModel", "structIRockyDeviceModel.xhtml", null ],
    [ "IRockyFluidScalars", "structIRockyFluidScalars.xhtml", null ],
    [ "IRockyFluidScalarsModel", "structIRockyFluidScalarsModel.xhtml", null ],
    [ "IRockyGeometriesMotionData", "structIRockyGeometriesMotionData.xhtml", null ],
    [ "IRockyGeometryMotionData", "structIRockyGeometryMotionData.xhtml", null ],
    [ "IRockyGeometryScalars", "structIRockyGeometryScalars.xhtml", null ],
    [ "IRockyGeometryScalarsModel", "structIRockyGeometryScalarsModel.xhtml", null ],
    [ "IRockyGeometryTriangle", "structIRockyGeometryTriangle.xhtml", null ],
    [ "IRockyGeometryTriangleHost", "structIRockyGeometryTriangleHost.xhtml", null ],
    [ "IRockyInteractionCalculationsData", "classIRockyInteractionCalculationsData.xhtml", [
      [ "IRockyAdhesiveDistanceData", "classIRockyAdhesiveDistanceData.xhtml", null ],
      [ "IRockyTimestepData", "classIRockyTimestepData.xhtml", null ]
    ] ],
    [ "IRockyJoint", "structIRockyJoint.xhtml", null ],
    [ "IRockyJointScalars", "structIRockyJointScalars.xhtml", null ],
    [ "IRockyJointScalarsModel", "structIRockyJointScalarsModel.xhtml", null ],
    [ "IRockyMaterial", "structIRockyMaterial.xhtml", null ],
    [ "IRockyMaterialInteraction", "structIRockyMaterialInteraction.xhtml", null ],
    [ "IRockyModel", "structIRockyModel.xhtml", null ],
    [ "IRockyOutputPropertyCollection", "structIRockyOutputPropertyCollection.xhtml", null ],
    [ "IRockyPairScalars", "structIRockyPairScalars.xhtml", null ],
    [ "IRockyPairScalarsModel", "structIRockyPairScalarsModel.xhtml", null ],
    [ "IRockyParticle", "structIRockyParticle.xhtml", null ],
    [ "IRockyParticleBreakageScalars", "structIRockyParticleBreakageScalars.xhtml", null ],
    [ "IRockyParticleBreakageScalarsModel", "structIRockyParticleBreakageScalarsModel.xhtml", null ],
    [ "IRockyParticleHost", "structIRockyParticleHost.xhtml", null ],
    [ "IRockyParticleScalars", "structIRockyParticleScalars.xhtml", null ],
    [ "IRockyParticleScalarsModel", "structIRockyParticleScalarsModel.xhtml", null ],
    [ "IRockyParticleTransferScalars", "structIRockyParticleTransferScalars.xhtml", null ],
    [ "IRockyParticleTransferScalarsModel", "structIRockyParticleTransferScalarsModel.xhtml", null ],
    [ "IRockyPluginData", "classIRockyPluginData.xhtml", null ],
    [ "IRockyPluginDataEntry", "classIRockyPluginDataEntry.xhtml", null ],
    [ "IRockySPHDeviceModel", "structIRockySPHDeviceModel.xhtml", null ],
    [ "IRockySPHElement", "structIRockySPHElement.xhtml", [
      [ "IRockySPHElementHost", "structIRockySPHElementHost.xhtml", null ]
    ] ],
    [ "IRockySPHElementInteraction", "structIRockySPHElementInteraction.xhtml", null ],
    [ "IRockySPHElementScalars", "structIRockySPHElementScalars.xhtml", null ],
    [ "IRockySPHElementScalarsModel", "structIRockySPHElementScalarsModel.xhtml", null ],
    [ "IRockySPHModel", "structIRockySPHModel.xhtml", null ],
    [ "IRockySPHTriangleInteraction", "structIRockySPHTriangleInteraction.xhtml", null ],
    [ "IRockyStatisticsAccumulator", "structIRockyStatisticsAccumulator.xhtml", null ],
    [ "IRockyStatisticsAdder", "structIRockyStatisticsAdder.xhtml", null ],
    [ "IRockyTriangleScalars", "structIRockyTriangleScalars.xhtml", null ],
    [ "IRockyTriangleScalarsModel", "structIRockyTriangleScalarsModel.xhtml", null ],
    [ "IRockyVicinityPair", "structIRockyVicinityPair.xhtml", null ]
];